export const VIM_HELP = [
  'HumanOS vim - Help',
  '',
  'Normal: hjkl / arrows move; 0 / $ line start / end; ^ first nonblank.',
  'w / b / e: next word / previous word / word end; W / B / E: whitespace words.',
  'gg / G: first / last line; %: matching bracket; PageUp / PageDown: scroll.',
  'f/F CHAR: find right/left; t/T CHAR: till character; ; / , repeat/reverse.',
  'i / a insert before / after cursor; I / A insert at first nonblank / end.',
  'o / O open a line below / above. Esc or Ctrl+C returns to Normal.',
  'd / c / y + motion: delete / change / copy; dw, c$, ye, dG, d/search.',
  'dd / cc / yy: delete / change / copy lines. Counts multiply: 2d3w.',
  'x deletes characters; D / C deletes / changes to line end; r CHAR replaces.',
  'p / P pastes after / before the cursor (below / above for copied lines).',
  'u undoes one edit; Ctrl+R redoes it. One Insert session is one edit.',
  'Counts: 3j, 2x, 3dd, 2yy; 5G / 5gg goes to line 5 (maximum 10000).',
  '/PATTERN / ?PATTERN: forward / backward search; n / N repeat / reverse.',
  'Search wraps at file edges. Empty pattern repeats the previous pattern.',
  ':s/old/new/ substitutes on this line; :%s/old/new/g substitutes everywhere.',
  ':2,5s/old/new/gi limits lines and ignores case; . is this line, $ the last.',
  'Patterns use JavaScript Unicode regex syntax: (groups), [classes], ^, $.',
  'Replacement: & = match, \\1..\\9 = groups, \\& = literal &, \\r = new line.',
  'Alternate delimiters and empty patterns work: :s#path/to#new/path#g.',
  'A substitution or change plus inserted text is one undo step.',
  ':w [FILE] saves; :q quits; :wq [FILE] saves and quits.',
  ':q! discards unsaved changes; :NUMBER goes to a line; :help shows keys.',
  'Command line: Backspace erases, Ctrl+U clears, Esc cancels.',
  ':set number / nonumber (nu): show / hide line numbers.',
  ':set hlsearch / nohlsearch (hls): highlight all search matches / disable.',
  ':noh clears highlights until the next search; :set wrap / nowrap: soft wrap.',
  ':set lists options; :set nu? queries; :set nu! toggles; :set nu& resets.',
  ':set cursorline / nocursorline (cul): gray background for the current line.',
  'Default: nonumber, hlsearch, wrap, cursorline. Current line number is bright.',
  'Startup reads $HOME/.vimrc (account home when HOME is unset).',
  '.vimrc supports set lines, blank lines, and double-quote comments.',
  'Configuration errors are reported with line numbers; other valid lines apply.',
  'Interactive settings override startup settings for this session only.',
  'Wrapped rows keep logical line numbers; paging moves by screen rows.',
  'Paste text in Insert mode. A named alternative save path must be new.',
  'Single file only; no visual mode, text objects, or named registers.',
]
